title:              NSL
email:              hello@nirajkhatiwada.com.np
description:        '"Thoughts and Experiments"'
author:             nerrorsec
baseurl:            "/"
url:                "https://nerrorsec.github.io"

# Social Profiles
twitter_username:   nerrorsec
github_username:    nerrorsec
linkedin_username:  nerrorsec
youtube_username:   nerrorsec

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
